apiVersion: v2
name: scrumlr
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
- name: nats
  version: 7.6.1
  repository: https://charts.bitnami.com/bitnami
  alias: nats
- name: postgresql
  version: 12.2.7
  repository: https://charts.bitnami.com/bitnami
  alias: postgresql
