hostname:

oauthroute:
  enabled: true

frontend:
  name: frontend
  image: ghcr.io/inovex/scrumlr.io/scrumlr-frontend:3.2.1
  imagePullPolicy:
  ingress:
    className: nginx
    annotations: {}
  replicas: 2


server:
  name: server
  image: ghcr.io/inovex/scrumlr.io/scrumlr-server:3.2.1
  imagePullPolicy:
  ingress:
    className: nginx
    annotations: {}
  replicas: 2

nats:
  fullnameOverride: scrumlr-cache
  auth:
    enabled: false
    # username: admin
    # password: password

postgresql:
  fullnameOverride: scrumlr-database
  auth:
    username: admin
    password: password
    database: scrumlr
    postgresPassword: supersecret
