apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "scrumlr-fullname" .Values.server }}
  labels:
    {{- include "selectorLabels" .Values.server | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
  {{- with .Values.server.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.server.ingress.className }}
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "scrumlr-fullname" .Values.server }}
            port:
              number: 8080
  {{- if .Values.hostname }}
    host: {{ .Values.hostname }}
  {{- end}}
