apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scrumlr-fullname" .Values.frontend }}
  labels: 
    {{- include "selectorLabels" .Values.frontend | nindent 6}}
    {{- include "labels" . | nindent 6}}
spec:
  replicas: {{ .Values.frontend.replicas | default 1}} 
  selector:
    matchLabels:
      {{- include "selectorLabels" .Values.frontend | nindent 8}}
  template:
    metadata:
      labels: 
        {{- include "selectorLabels" .Values.frontend | nindent 8 }}    
    spec:
      containers:
        - name: {{ include "scrumlr-fullname" .Values.frontend }}
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
          env:
          - name: SCRUMLR_SERVER_URL
            value: /api
          - name: SCRUMLR_SHOW_LEGAL_DOCUMENTS
            value: "true"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe: 
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always
