apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrumlr-fullname" .Values.frontend }}
  labels: 
    {{- include "selectorLabels" .Values.frontend | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    {{- include "selectorLabels" .Values.frontend | nindent 6 }}
