apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrumlr-fullname" .Values.frontend }}
  labels: 
    {{- include "selectorLabels" .Values.frontend | nindent 6 }}
    {{- include "labels" . | nindent 6 }}
spec:
  {{- if .Values.minikube.enabled }}
  type: LoadBalancer
  {{- end }}
  ports:
    - port: 80 
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "selectorLabels" .Values.frontend | nindent 6 }}
